BEGIN;

-- 以降の SQL を app, public スキーマ の 順で使う
SET search_path TO app, public;

INSERT INTO capital_coin (
    id
  , symbol
  , coin_market_cap_id
  , created_at
  , updated_at
)
VALUES
  (1, 'BTC', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (2, 'ETH', 1027, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (3, 'DOT', 6636, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (4, 'BAT', 1697, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (5, 'ENJ', 2130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (6, 'XTZ', 2011, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
, (7, 'ATOM', 3794, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;

COMMIT;
