apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${CR_SERVICE}
spec:
  template:
    metadata:
      # インスタンスの設定
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 50
      timeoutSeconds: 300
      # Cloud Run に付与する 専用の サービスアカウント
      serviceAccountName: ${CR_SERVICE_ACCOUNT}@${GCP_PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: ${DOCKER_IMAGE}
        ports:
        - name: http1
          containerPort: ${CR_PORT}
        env:
        - name: IS_CLOUD
          value: 'true'
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        # ヘルスチェック の 項目らしい
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: ${CR_PORT}
  traffic:
  - percent: 100
    latestRevision: true
